apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: homepage
type: Opaque
stringData:
  POSTGRES_DB: homepage_db
  POSTGRES_USER: homepage_user
  POSTGRES_PASSWORD: homepage_password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: homepage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn   # ★ RKE2/Harvester 환경에서 가장 안정적
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432

          # ★ Postgres가 PVC 권한 오류 없이 안정적으로 동작하도록 추가
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgres-secret

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

          # ★ 안정성 증가를 위한 liveness/readiness probe 추가
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "homepage_user"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "homepage_user"]
            initialDelaySeconds: 20
            periodSeconds: 10

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: homepage
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
